repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    #При первом запуске скачивает из репозитория ruff
    #можно использовать repo: local
    rev: v0.1.13
    hooks:
      - id: ruff
      - id: ruff-format