services:
  
  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=test_base

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080