line-length = 88

[lint]
select = [
    "E",  # pycodestyle errors https://docs.astral.sh/ruff/rules/#error-e
    "W",  # pycodestyle warnings https://docs.astral.sh/ruff/rules/#warning-w
    "F",  # pyflakes https://docs.astral.sh/ruff/rules/#pyflakes-f
    "I",  # isort https://docs.astral.sh/ruff/rules/#isort-i
    "B",  # flake8-bugbear https://docs.astral.sh/ruff/rules/#flake8-bugbear-b
    "C4",  # flake8-comprehensions
    "UP",  # pyupgrade
]